name: Hello Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello GitHub Actions 🚀"
